In [ ]:
import pandas as pd
from google.colab import drive
import numpy as np
from datetime import datetime

drive.mount('/content/drive')

path = '/content/drive/MyDrive/daily_activity.csv'

import pandas as pd
df = pd.read_csv(path)
df

Mounted at /content/drive

,Id,ActivityDate,Unnamed: 2,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,NaN,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,NaN,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,NaN,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,NaN,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,NaN,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,8877708929,10/9/2017,NaN,8762,2.34,19539.78,19538.0,19538.00,19538.00,19539.78,19538.0,19538,19538,19596,20069,20476
19995,8877708930,10/10/2017,NaN,1530,11.18,19540.78,19539.0,19539.00,19539.00,19540.78,19539.0,19539,19539,19597,20070,20477
19996,8877708931,10/11/2017,NaN,13450,18.60,19541.78,19540.0,19540.00,19540.00,19541.78,19540.0,19540,19540,19598,20071,20478
19997,8877708932,10/12/2017,NaN,15184,9.63,19542.78,19541.0,19541.00,19541.00,19542.78,19541.0,19541,19541,19599,20072,20479
19998,8877708933,10/13/2017,NaN,11393,9.92,19543.78,19542.0,19542.00,19542.00,19543.78,19542.0,19542,19542,19600,20073,20480

In [ ]:
import pandas as pd

def find_date_column(df):
    possible_date_cols = []

    for col in df.columns:
        try:
            parsed = pd.to_datetime(df[col], errors='coerce')  # Convert to datetime
            valid_dates = parsed.notna().sum() / len(df)  # Percentage of valid entries

            # Ensure column was originally non-numeric before conversion
            is_object_or_string = df[col].dtype == "object" or pd.api.types.is_string_dtype(df[col])

            print(f"🔎 Checking '{col}': {valid_dates:.2%} valid dates | Type: {df[col].dtype}")  # Debugging

            if valid_dates > 0.6 and is_object_or_string:  # At least 60% valid dates & originally text-based
                possible_date_cols.append(col)
        except Exception as e:
            print(f"⚠️ Error processing '{col}': {e}")

    return possible_date_cols[0] if possible_date_cols else None

# Example usage:
date_col = find_date_column(df)
print(f"📅 Detected date column: {date_col}" if date_col else "❌ No date column detected!")

🔎 Checking 'Id': 100.00% valid dates | Type: int64
🔎 Checking 'ActivityDate': 100.00% valid dates | Type: object
🔎 Checking 'Unnamed: 2': 0.01% valid dates | Type: object
🔎 Checking 'TotalSteps': 100.00% valid dates | Type: int64
🔎 Checking 'TotalDistance': 100.00% valid dates | Type: float64
🔎 Checking 'TrackerDistance': 100.00% valid dates | Type: float64
🔎 Checking 'LoggedActivitiesDistance': 100.00% valid dates | Type: float64
🔎 Checking 'VeryActiveDistance': 100.00% valid dates | Type: float64
🔎 Checking 'ModeratelyActiveDistance': 100.00% valid dates | Type: float64
🔎 Checking 'LightActiveDistance': 100.00% valid dates | Type: float64
🔎 Checking 'SedentaryActiveDistance': 100.00% valid dates | Type: float64
🔎 Checking 'VeryActiveMinutes': 100.00% valid dates | Type: int64
🔎 Checking 'FairlyActiveMinutes': 100.00% valid dates | Type: int64
🔎 Checking 'LightlyActiveMinutes': 100.00% valid dates | Type: int64
🔎 Checking 'SedentaryMinutes': 100.00% valid dates | Type: int64
🔎 Checking 'Calories': 100.00% valid dates | Type: int64
📅 Detected date column: ActivityDate

In [ ]:
df.loc[df.index[-50:], date_col] = pd.to_datetime(df[date_col], errors='coerce').dt.strftime('%B %d, %Y')

print(df)

count_written = df[date_col].astype(str).str.match(r'^[A-Za-z]+ \d{1,2}, \d{4}$').sum()
print(f"{count_written} dates are in written format! This data is inconsistent. Consider makeing entire {date_col} column the same format.")

               Id      ActivityDate Unnamed: 2  TotalSteps  TotalDistance  \
0      1503960366         3/25/2016        NaN       11004           7.11
1      1503960366         3/26/2016        NaN       17609          11.55
2      1503960366         3/27/2016        NaN       12736           8.53
3      1503960366         3/28/2016        NaN       13231           8.93
4      1503960366         3/29/2016        NaN       12041           7.85
...           ...               ...        ...         ...            ...
19994  8877708929  October 09, 2017        NaN        8762           2.34
19995  8877708930  October 10, 2017        NaN        1530          11.18
19996  8877708931  October 11, 2017        NaN       13450          18.60
19997  8877708932  October 12, 2017        NaN       15184           9.63
19998  8877708933  October 13, 2017        NaN       11393           9.92

       TrackerDistance  LoggedActivitiesDistance  VeryActiveDistance  \
0                 7.11                       0.0                2.57
1                11.55                       0.0                6.92
2                 8.53                       0.0                4.66
3                 8.93                       0.0                3.19
4                 7.85                       0.0                2.16
...                ...                       ...                 ...
19994         19539.78                   19538.0            19538.00
19995         19540.78                   19539.0            19539.00
19996         19541.78                   19540.0            19540.00
19997         19542.78                   19541.0            19541.00
19998         19543.78                   19542.0            19542.00

       ModeratelyActiveDistance  LightActiveDistance  SedentaryActiveDistance  \
0                          0.46                 4.07                      0.0
1                          0.73                 3.91                      0.0
2                          0.16                 3.71                      0.0
3                          0.79                 4.95                      0.0
4                          1.09                 4.61                      0.0
...                         ...                  ...                      ...
19994                  19538.00             19539.78                  19538.0
19995                  19539.00             19540.78                  19539.0
19996                  19540.00             19541.78                  19540.0
19997                  19541.00             19542.78                  19541.0
19998                  19542.00             19543.78                  19542.0

       VeryActiveMinutes  FairlyActiveMinutes  LightlyActiveMinutes  \
0                     33                   12                   205
1                     89                   17                   274
2                     56                    5                   268
3                     39                   20                   224
4                     28                   28                   243
...                  ...                  ...                   ...
19994              19538                19538                 19596
19995              19539                19539                 19597
19996              19540                19540                 19598
19997              19541                19541                 19599
19998              19542                19542                 19600

       SedentaryMinutes  Calories
0                   804      1819
1                   588      2154
2                   605      1944
3                  1080      1932
4                   763      1886
...                 ...       ...
19994             20069     20476
19995             20070     20477
19996             20071     20478
19997             20072     20479
19998             20073     20480

[19999 rows x 16 columns]
50 dates are in written format! This data is inconsistent. Consider makeing entire ActivityDate column the same format.

In [ ]:
def format_date_columns(df, date_cols, format_string):
    # Ensure date_cols is a list even if a single column name is passed as a string
    if isinstance(date_cols, str):
        date_cols = [date_cols]

    for col in date_cols:
      # Use errors='coerce' in to_datetime to handle potential parsing issues
      df[col] = pd.to_datetime(df[col], errors='coerce', format='mixed').dt.strftime(format_string)
    return df

format_string = '%Y-%m-%d' # Desired output format

# Pass date_col as a list containing the column name
df = format_date_columns(df, date_col, format_string)
print(df)

count_written = df[date_col].astype(str).str.match(r'^[A-Za-z]+ \d{1,2}, \d{4}$').sum()

print(f"{count_written} dates are in written format! {date_col} column is now in the same format. This data is now consistent.")

               Id ActivityDate Unnamed: 2  TotalSteps  TotalDistance  \
0      1503960366   2016-03-25        NaN       11004           7.11
1      1503960366   2016-03-26        NaN       17609          11.55
2      1503960366   2016-03-27        NaN       12736           8.53
3      1503960366   2016-03-28        NaN       13231           8.93
4      1503960366   2016-03-29        NaN       12041           7.85
...           ...          ...        ...         ...            ...
19994  8877708929   2017-10-09        NaN        8762           2.34
19995  8877708930   2017-10-10        NaN        1530          11.18
19996  8877708931   2017-10-11        NaN       13450          18.60
19997  8877708932   2017-10-12        NaN       15184           9.63
19998  8877708933   2017-10-13        NaN       11393           9.92

       TrackerDistance  LoggedActivitiesDistance  VeryActiveDistance  \
0                 7.11                       0.0                2.57
1                11.55                       0.0                6.92
2                 8.53                       0.0                4.66
3                 8.93                       0.0                3.19
4                 7.85                       0.0                2.16
...                ...                       ...                 ...
19994         19539.78                   19538.0            19538.00
19995         19540.78                   19539.0            19539.00
19996         19541.78                   19540.0            19540.00
19997         19542.78                   19541.0            19541.00
19998         19543.78                   19542.0            19542.00

       ModeratelyActiveDistance  LightActiveDistance  SedentaryActiveDistance  \
0                          0.46                 4.07                      0.0
1                          0.73                 3.91                      0.0
2                          0.16                 3.71                      0.0
3                          0.79                 4.95                      0.0
4                          1.09                 4.61                      0.0
...                         ...                  ...                      ...
19994                  19538.00             19539.78                  19538.0
19995                  19539.00             19540.78                  19539.0
19996                  19540.00             19541.78                  19540.0
19997                  19541.00             19542.78                  19541.0
19998                  19542.00             19543.78                  19542.0

       VeryActiveMinutes  FairlyActiveMinutes  LightlyActiveMinutes  \
0                     33                   12                   205
1                     89                   17                   274
2                     56                    5                   268
3                     39                   20                   224
4                     28                   28                   243
...                  ...                  ...                   ...
19994              19538                19538                 19596
19995              19539                19539                 19597
19996              19540                19540                 19598
19997              19541                19541                 19599
19998              19542                19542                 19600

       SedentaryMinutes  Calories
0                   804      1819
1                   588      2154
2                   605      1944
3                  1080      1932
4                   763      1886
...                 ...       ...
19994             20069     20476
19995             20070     20477
19996             20071     20478
19997             20072     20479
19998             20073     20480

[19999 rows x 16 columns]
0 dates are in written format! ActivityDate column is now in the same format. This data is now consistent.