In [ ]:
import pandas as pd
from google.colab import drive
import numpy as np
from datetime import datetime

drive.mount('/content/drive')

path = '/content/drive/MyDrive/Chicago_Public_Schools_-_School_Admissions_Information_SY2324.csv'

import pandas as pd
df = pd.read_csv(path)
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,School_ID,Short_Name,Long_Name,Primary_Category,Program_Type,Program_Group,Address,City,State,Zip,...,CPS_School_Profile,Website,Program_Grades_Served,Application_Requirements,Program_Selections,How_To_Apply,Deadline,School_Latitude,School_Longitude,Location
0,610026,KINZIE,John H Kinzie Elementary School,ES,KINZIE-Open Enrollment-General Education,General Education,5625 S MOBILE AVE,Chicago,Illinois,60638,...,https://www.cps.edu/schools/schoolprofiles/610026,http://kinzie.cps.edu,"K,1,2,3,4,5",NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.789965,-87.779483,POINT (-87.779483 41.789965)
1,610078,INTER-AMERICAN,Inter-American Elementary Magnet School,ES,INTER-AMERICAN-Magnet-Dual Language,Dual Language,851 W WAVELAND AVE,Chicago,Illinois,60613,...,https://www.cps.edu/schools/schoolprofiles/610078,https://iamschicago.com,"PreK,K,1,2,3,4,5,6,7",NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.949003,-87.651573,POINT (-87.651573 41.949003)
2,609756,CURIE HS,Marie Sklodowska Curie Metropolitan High School,HS,CURIE HS-Career & Technical Education (CTE)-Me...,Media & Communication Arts,4959 S ARCHER AVE,Chicago,Illinois,60632,...,https://www.cps.edu/schools/schoolprofiles/609756,https://www.curiehs.org,9,NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.803060,-87.722042,POINT (-87.722042 41.80306)
3,609756,CURIE HS,Marie Sklodowska Curie Metropolitan High School,HS,CURIE HS-Career & Technical Education (CTE)-Me...,Media & Communication Arts,4959 S ARCHER AVE,Chicago,Illinois,60632,...,https://www.cps.edu/schools/schoolprofiles/609756,https://www.curiehs.org,9,NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.803060,-87.722042,POINT (-87.722042 41.80306)
4,610039,VON LINNE,Carl von Linne Elementary School,ES,VON LINNE-Open Enrollment-General Education,General Education,3221 N SACRAMENTO AVE,Chicago,Illinois,60618,...,https://www.cps.edu/schools/schoolprofiles/610039,https://www.linneschool.org,"K,1,2,3,4,5,6,7,8",NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.940009,-87.702635,POINT (-87.702635 41.940009)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,609738,LINCOLN PARK HS,Lincoln Park High School,HS,LINCOLN PARK HS-Neighborhood-Fine & Performing...,Fine & Performing Arts,2001 N ORCHARD ST,Chicago,Illinois,60614,...,https://www.cps.edu/schools/schoolprofiles/609738,https://www.lincolnparkhs.org,9,Portfolio Review,<ul><li><strong>Selection Type: </strong>Desce...,Portfolio Review,NaN,41.918268,-87.646009,POINT (-87.646009 41.918268)
931,610073,MITCHELL,Ellen Mitchell Elementary School,ES,MITCHELL-Open Enrollment-General Education,General Education,2233 W OHIO ST,Chicago,Illinois,60612,...,https://www.cps.edu/schools/schoolprofiles/610073,https://mitchellschool.org,"K,1,2,3,4,5,6,7,8",NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.892082,-87.683185,POINT (-87.683185 41.892082)
932,610518,AUSTIN CCA HS,Austin College and Career Academy High School,HS,AUSTIN CCA HS-Career & Technical Education (CT...,Manufacturing & Engineering,231 N PINE AVE,Chicago,Illinois,60644,...,https://www.cps.edu/schools/schoolprofiles/610518,https://accachicago.cps.edu,9,NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.885993,-87.761916,POINT (-87.761916 41.885993)
933,610041,LOCKE J,Josephine C Locke Elementary School,ES,LOCKE J-Magnet Cluster-IB Middle Years Programme,IB Middle Years Programme,2828 N OAK PARK AVE,Chicago,Illinois,60634,...,https://www.cps.edu/schools/schoolprofiles/610041,https://lockeschool.org,8-Jun,NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.931762,-87.795604,POINT (-87.795604 41.931762)
934,610369,JACKSON M,Mahalia Jackson Elementary School,ES,JACKSON M-Open Enrollment-General Education,General Education,917 W 88TH ST,Chicago,Illinois,60620,...,https://www.cps.edu/schools/schoolprofiles/610369,http://www.mjacksoncps.com/,"K,1,2,3,4,5,6,7,8",NaN,<ul><li><strong>Selection Type: </strong>Rando...,NaN,NaN,41.734125,-87.646767,POINT (-87.646767 41.734125)

In [ ]:
import pandas as pd

df_remove = df

def readd_first_three_cols(df_remove):
    # Store the first 3 columns
    first_three_cols = df_remove.iloc[:, :3]

    # Delete the first 3 columns
    df_remove = df_remove.iloc[:, 3:]

    return df_remove

print("Original DataFrame:")
print(df)

df_remove = readd_first_three_cols(df_remove)
print("\nDataFrame with first 3 columns deleted:")
print(df_remove)

Original DataFrame:
     School_ID       Short_Name  \
0       610026           KINZIE
1       610078   INTER-AMERICAN
2       609756         CURIE HS
3       609756         CURIE HS
4       610039        VON LINNE
..         ...              ...
930     609738  LINCOLN PARK HS
931     610073         MITCHELL
932     610518    AUSTIN CCA HS
933     610041          LOCKE J
934     610369        JACKSON M

                                           Long_Name Primary_Category  \
0                    John H Kinzie Elementary School               ES
1            Inter-American Elementary Magnet School               ES
2    Marie Sklodowska Curie Metropolitan High School               HS
3    Marie Sklodowska Curie Metropolitan High School               HS
4                   Carl von Linne Elementary School               ES
..                                               ...              ...
930                         Lincoln Park High School               HS
931                 Ellen Mitchell Elementary School               ES
932    Austin College and Career Academy High School               HS
933              Josephine C Locke Elementary School               ES
934                Mahalia Jackson Elementary School               ES

                                          Program_Type  \
0             KINZIE-Open Enrollment-General Education
1                  INTER-AMERICAN-Magnet-Dual Language
2    CURIE HS-Career & Technical Education (CTE)-Me...
3    CURIE HS-Career & Technical Education (CTE)-Me...
4          VON LINNE-Open Enrollment-General Education
..                                                 ...
930  LINCOLN PARK HS-Neighborhood-Fine & Performing...
931         MITCHELL-Open Enrollment-General Education
932  AUSTIN CCA HS-Career & Technical Education (CT...
933   LOCKE J-Magnet Cluster-IB Middle Years Programme
934        JACKSON M-Open Enrollment-General Education

                   Program_Group                Address     City     State  \
0              General Education      5625 S MOBILE AVE  Chicago  Illinois
1                  Dual Language     851 W WAVELAND AVE  Chicago  Illinois
2     Media & Communication Arts      4959 S ARCHER AVE  Chicago  Illinois
3     Media & Communication Arts      4959 S ARCHER AVE  Chicago  Illinois
4              General Education  3221 N SACRAMENTO AVE  Chicago  Illinois
..                           ...                    ...      ...       ...
930       Fine & Performing Arts      2001 N ORCHARD ST  Chicago  Illinois
931            General Education         2233 W OHIO ST  Chicago  Illinois
932  Manufacturing & Engineering         231 N PINE AVE  Chicago  Illinois
933    IB Middle Years Programme    2828 N OAK PARK AVE  Chicago  Illinois
934            General Education          917 W 88TH ST  Chicago  Illinois

       Zip  ...                                 CPS_School_Profile  \
0    60638  ...  https://www.cps.edu/schools/schoolprofiles/610026
1    60613  ...  https://www.cps.edu/schools/schoolprofiles/610078
2    60632  ...  https://www.cps.edu/schools/schoolprofiles/609756
3    60632  ...  https://www.cps.edu/schools/schoolprofiles/609756
4    60618  ...  https://www.cps.edu/schools/schoolprofiles/610039
..     ...  ...                                                ...
930  60614  ...  https://www.cps.edu/schools/schoolprofiles/609738
931  60612  ...  https://www.cps.edu/schools/schoolprofiles/610073
932  60644  ...  https://www.cps.edu/schools/schoolprofiles/610518
933  60634  ...  https://www.cps.edu/schools/schoolprofiles/610041
934  60620  ...  https://www.cps.edu/schools/schoolprofiles/610369

                           Website Program_Grades_Served  \
0            http://kinzie.cps.edu           K,1,2,3,4,5
1          https://iamschicago.com  PreK,K,1,2,3,4,5,6,7
2          https://www.curiehs.org                     9
3          https://www.curiehs.org                     9
4      https://www.linneschool.org     K,1,2,3,4,5,6,7,8
..                             ...                   ...
930  https://www.lincolnparkhs.org                     9
931     https://mitchellschool.org     K,1,2,3,4,5,6,7,8
932    https://accachicago.cps.edu                     9
933        https://lockeschool.org                 8-Jun
934    http://www.mjacksoncps.com/     K,1,2,3,4,5,6,7,8

    Application_Requirements  \
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
..                       ...
930         Portfolio Review
931                      NaN
932                      NaN
933                      NaN
934                      NaN

                                    Program_Selections      How_To_Apply  \
0    <ul><li><strong>Selection Type: </strong>Rando...               NaN
1    <ul><li><strong>Selection Type: </strong>Rando...               NaN
2    <ul><li><strong>Selection Type: </strong>Rando...               NaN
3    <ul><li><strong>Selection Type: </strong>Rando...               NaN
4    <ul><li><strong>Selection Type: </strong>Rando...               NaN
..                                                 ...               ...
930  <ul><li><strong>Selection Type: </strong>Desce...  Portfolio Review
931  <ul><li><strong>Selection Type: </strong>Rando...               NaN
932  <ul><li><strong>Selection Type: </strong>Rando...               NaN
933  <ul><li><strong>Selection Type: </strong>Rando...               NaN
934  <ul><li><strong>Selection Type: </strong>Rando...               NaN

    Deadline School_Latitude  School_Longitude                      Location
0        NaN       41.789965        -87.779483  POINT (-87.779483 41.789965)
1        NaN       41.949003        -87.651573  POINT (-87.651573 41.949003)
2        NaN       41.803060        -87.722042   POINT (-87.722042 41.80306)
3        NaN       41.803060        -87.722042   POINT (-87.722042 41.80306)
4        NaN       41.940009        -87.702635  POINT (-87.702635 41.940009)
..       ...             ...               ...                           ...
930      NaN       41.918268        -87.646009  POINT (-87.646009 41.918268)
931      NaN       41.892082        -87.683185  POINT (-87.683185 41.892082)
932      NaN       41.885993        -87.761916  POINT (-87.761916 41.885993)
933      NaN       41.931762        -87.795604  POINT (-87.795604 41.931762)
934      NaN       41.734125        -87.646767  POINT (-87.646767 41.734125)

[935 rows x 22 columns]

DataFrame with first 3 columns deleted:
    Primary_Category                                       Program_Type  \
0                 ES           KINZIE-Open Enrollment-General Education
1                 ES                INTER-AMERICAN-Magnet-Dual Language
2                 HS  CURIE HS-Career & Technical Education (CTE)-Me...
3                 HS  CURIE HS-Career & Technical Education (CTE)-Me...
4                 ES        VON LINNE-Open Enrollment-General Education
..               ...                                                ...
930               HS  LINCOLN PARK HS-Neighborhood-Fine & Performing...
931               ES         MITCHELL-Open Enrollment-General Education
932               HS  AUSTIN CCA HS-Career & Technical Education (CT...
933               ES   LOCKE J-Magnet Cluster-IB Middle Years Programme
934               ES        JACKSON M-Open Enrollment-General Education

                   Program_Group                Address     City     State  \
0              General Education      5625 S MOBILE AVE  Chicago  Illinois
1                  Dual Language     851 W WAVELAND AVE  Chicago  Illinois
2     Media & Communication Arts      4959 S ARCHER AVE  Chicago  Illinois
3     Media & Communication Arts      4959 S ARCHER AVE  Chicago  Illinois
4              General Education  3221 N SACRAMENTO AVE  Chicago  Illinois
..                           ...                    ...      ...       ...
930       Fine & Performing Arts      2001 N ORCHARD ST  Chicago  Illinois
931            General Education         2233 W OHIO ST  Chicago  Illinois
932  Manufacturing & Engineering         231 N PINE AVE  Chicago  Illinois
933    IB Middle Years Programme    2828 N OAK PARK AVE  Chicago  Illinois
934            General Education          917 W 88TH ST  Chicago  Illinois

       Zip       Phone           Fax  \
0    60638  7735352425  7.735352e+09
1    60613  7735345490  7.735345e+09
2    60632  7735352100  7.735352e+09
3    60632  7735352100  7.735352e+09
4    60618  7735345262  7.735345e+09
..     ...         ...           ...
930  60614  7735348130  7.735348e+09
931  60612  7735347655  7.735348e+09
932  60644  7735340660  7.735346e+09
933  60634  7735343300  7.735343e+09
934  60620  7735353341  7.735353e+09

                                    CPS_School_Profile  \
0    https://www.cps.edu/schools/schoolprofiles/610026
1    https://www.cps.edu/schools/schoolprofiles/610078
2    https://www.cps.edu/schools/schoolprofiles/609756
3    https://www.cps.edu/schools/schoolprofiles/609756
4    https://www.cps.edu/schools/schoolprofiles/610039
..                                                 ...
930  https://www.cps.edu/schools/schoolprofiles/609738
931  https://www.cps.edu/schools/schoolprofiles/610073
932  https://www.cps.edu/schools/schoolprofiles/610518
933  https://www.cps.edu/schools/schoolprofiles/610041
934  https://www.cps.edu/schools/schoolprofiles/610369

                           Website Program_Grades_Served  \
0            http://kinzie.cps.edu           K,1,2,3,4,5
1          https://iamschicago.com  PreK,K,1,2,3,4,5,6,7
2          https://www.curiehs.org                     9
3          https://www.curiehs.org                     9
4      https://www.linneschool.org     K,1,2,3,4,5,6,7,8
..                             ...                   ...
930  https://www.lincolnparkhs.org                     9
931     https://mitchellschool.org     K,1,2,3,4,5,6,7,8
932    https://accachicago.cps.edu                     9
933        https://lockeschool.org                 8-Jun
934    http://www.mjacksoncps.com/     K,1,2,3,4,5,6,7,8

    Application_Requirements  \
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
..                       ...
930         Portfolio Review
931                      NaN
932                      NaN
933                      NaN
934                      NaN

                                    Program_Selections      How_To_Apply  \
0    <ul><li><strong>Selection Type: </strong>Rando...               NaN
1    <ul><li><strong>Selection Type: </strong>Rando...               NaN
2    <ul><li><strong>Selection Type: </strong>Rando...               NaN
3    <ul><li><strong>Selection Type: </strong>Rando...               NaN
4    <ul><li><strong>Selection Type: </strong>Rando...               NaN
..                                                 ...               ...
930  <ul><li><strong>Selection Type: </strong>Desce...  Portfolio Review
931  <ul><li><strong>Selection Type: </strong>Rando...               NaN
932  <ul><li><strong>Selection Type: </strong>Rando...               NaN
933  <ul><li><strong>Selection Type: </strong>Rando...               NaN
934  <ul><li><strong>Selection Type: </strong>Rando...               NaN

     Deadline  School_Latitude  School_Longitude                      Location
0         NaN        41.789965        -87.779483  POINT (-87.779483 41.789965)
1         NaN        41.949003        -87.651573  POINT (-87.651573 41.949003)
2         NaN        41.803060        -87.722042   POINT (-87.722042 41.80306)
3         NaN        41.803060        -87.722042   POINT (-87.722042 41.80306)
4         NaN        41.940009        -87.702635  POINT (-87.702635 41.940009)
..        ...              ...               ...                           ...
930       NaN        41.918268        -87.646009  POINT (-87.646009 41.918268)
931       NaN        41.892082        -87.683185  POINT (-87.683185 41.892082)
932       NaN        41.885993        -87.761916  POINT (-87.761916 41.885993)
933       NaN        41.931762        -87.795604  POINT (-87.795604 41.931762)
934       NaN        41.734125        -87.646767  POINT (-87.646767 41.734125)

[935 rows x 19 columns]

In [ ]:


def compare_columns(df, df_remove):
    """
    Compares the columns of two DataFrames and prints the differences.

    Args:
        df1: The first DataFrame.
        df2: The second DataFrame.
    """
    cols1 = set(df.columns)
    cols2 = set(df_remove.columns)

    added_cols = cols2 - cols1
    removed_cols = cols1 - cols2
    common_cols = cols1.intersection(cols2)

    print("Columns missing that are needed to answer query:", removed_cols)



compare_columns(df, df_remove)

Columns missing that are needed to answer query: {'Long_Name', 'School_ID', 'Short_Name'}

In [ ]:
# List of required column names
required_columns =  df.iloc[:, :3]

# Check for missing columns and print a message
missing_columns = [col for col in required_columns if col not in df.columns]

if missing_columns:
    print(f"Error: The following required columns are missing from the DataFrame: {missing_columns}")
else:
    print("All required columns are now present in the DataFrame. The query can be answered.")

All required columns are now present in the DataFrame. The query can be answered.