In [ ]:
import pandas as pd
from google.colab import drive
import numpy as np
from datetime import datetime

drive.mount('/content/drive')

path = '/content/drive/MyDrive/LADOT_Metered_Parking_Inventory___Policies.csv'

import pandas as pd
df = pd.read_csv(path)
df

Mounted at /content/drive

,SpaceID,BlockFace,MeterType,RateType,RateRange,MeteredTimeLimit,LatLng
0,VH196,2100 HILLHURST AVE,Single-Space,FLAT,$1.00,1HR,"(34.111158, -118.287329)"
1,CB3019,101 4TH ST,Single-Space,TOD,$0.50 - $1.50,2HR,"(34.047747, -118.246658)"
2,MD153,1601 MARENGO ST,Single-Space,JUMP,$1.00/H - $4.00/10H,10HR,"(34.059023, -118.212624)"
3,UC189,3500 CAHUENGA BLVD,Single-Space,FLAT,$1.00,2HR,"(34.134309, -118.358778)"
4,CB2064,1401 MAPLE AVE,Single-Space,FLAT,$0.50,4HR,"(34.032899, -118.258656)"
...,...,...,...,...,...,...,...
33886,NH730,4100 LANKERSHIM BLVD,Single-Space,FLAT,$1.00,4HR,"(34.14388, -118.361776)"
33887,112693,801 TRACTION AVE,Multi-Space,FLAT,$1.00,2HR,"(34.043713, -118.233995)"
33888,112878,101 SANTA FE AVE,Multi-Space,FLAT,$1.00,2HR,"(34.048555, -118.232501)"
33889,WSV223,11900 WILSHIRE BLVD,Single-Space,FLAT,$1.00,1HR,"(34.046183, -118.464727)"
33890,NH573,5001 LANKERSHIM BLVD,Single-Space,FLAT,$1.00,2HR,"(34.162697, -118.373475)"

In [ ]:
import pandas as pd
import re
import numpy as np

def find_address_column(df):
    address_pattern = re.compile(r'\b\d+\s+\w+\s+(?:way|place|drive|lane|street|avenue|road|boulevard|wy|pl|dr|ln|st|ave|rd|blvd||Wy|Pl|St|Ave|Rd|Blvd|Dr|Ln|DRIVE|WAY|PLACE|LANE|STREET|AVENUE|BOULEVARD|ROAD|ST|DR|LN|WY|PL|AVE|RD|Way|Place|Drive|Lane|Boulevard|Street|Avenue|Road)\b', re.IGNORECASE)
    for column in df.columns:
        if df[column].astype(str).str.contains(address_pattern).any():
            return column
    return None


address_column = find_address_column(df)
if address_column:
    print(f"Address column found: {address_column}")
else:
    print("No address column found.")

Address column found: BlockFace

In [ ]:
import pandas as pd
import re

# Dictionary mapping abbreviations to full names
abbreviation_map = {
    "St": "Street",
    "Ave": "Avenue",
    "Rd": "Road",
    "Blvd": "Boulevard",
    "Dr": "Drive",
    "Ln": "Lane",
    "Wy": "Way",
    "Pl": "Place"
}

# Function to replace abbreviations safely using regex with word boundaries
def expand_abbreviations(address):
    for abbr, full in abbreviation_map.items():
        address = re.sub(rf'\b{abbr}\b', full, address, flags=re.IGNORECASE)  # Replace full words only
    return address

# Apply function **only to first 10 rows**
df.loc[:9, address_column] = df.loc[:9, address_column].astype(str).apply(expand_abbreviations)

# Print results
print(df.head(10))  # Show first 10 rows to verify

  SpaceID                BlockFace     MeterType RateType  \
0   VH196    2100 HILLHURST Avenue  Single-Space     FLAT
1  CB3019           101 4TH Street  Single-Space      TOD
2   MD153      1601 MARENGO Street  Single-Space     JUMP
3   UC189  3500 CAHUENGA Boulevard  Single-Space     FLAT
4  CB2064        1401 MAPLE Avenue  Single-Space     FLAT
5  WW2214      3000 PICO Boulevard  Single-Space     FLAT
6   MM102      701 DUNSMUIR Avenue  Single-Space     FLAT
7    WS97      1200 GLENDON Avenue  Single-Space     FLAT
8   BF306      7901 MELROSE Avenue  Single-Space     FLAT
9   MM122       700 DETROIT Street  Single-Space     FLAT

             RateRange MeteredTimeLimit                    LatLng
0                $1.00              1HR  (34.111158, -118.287329)
1        $0.50 - $1.50              2HR  (34.047747, -118.246658)
2  $1.00/H - $4.00/10H             10HR  (34.059023, -118.212624)
3                $1.00              2HR  (34.134309, -118.358778)
4                $0.50              4HR  (34.032899, -118.258656)
5                $1.00              1HR   (34.047114, -118.30805)
6                $1.00              2HR  (34.062027, -118.348432)
7                $1.00              2HR  (34.057814, -118.441914)
8                $1.00              2HR  (34.083899, -118.362209)
9                $1.00              2HR  (34.061447, -118.345375)

In [ ]:
import pandas as pd
import re

# Dictionary mapping full street names to abbreviations
full_to_abbreviation = {
    "Street": "St",
    "Avenue": "Ave",
    "Road": "Rd",
    "Boulevard": "Blvd",
    "Drive": "Dr",
    "Lane": "Ln",
    "Way": "Wy",
    "Place": "Pl"
}

# Function to abbreviate full street names (case-insensitive)
def abbreviate_address(address):
    for full_name, abbr in full_to_abbreviation.items():
        address = re.sub(rf'\b{full_name}\b', abbr, address, flags=re.IGNORECASE)  # Case-insensitive replacement
    return address

# Apply function **only to the last 10 rows**
df.loc[df.index[-10:], address_column] = df.loc[df.index[-10:], address_column].astype(str).apply(abbreviate_address)

# Print results
print(df.tail(10))  # Show last 10 rows to verify

      SpaceID                BlockFace     MeterType RateType  \
33881   NH773     4200 LANKERSHIM BLVD  Single-Space     FLAT
33882   BR120   11800 SAN VICENTE BLVD  Single-Space     FLAT
33883   EN219        16701 LA MAIDA ST  Single-Space     FLAT
33884   SO804  4201 VENTURA CANYON AVE  Single-Space     FLAT
33885   SC605       12500 VENTURA BLVD  Single-Space     JUMP
33886   NH730     4100 LANKERSHIM BLVD  Single-Space     FLAT
33887  112693         801 TRACTION AVE   Multi-Space     FLAT
33888  112878         101 SANTA FE AVE   Multi-Space     FLAT
33889  WSV223      11900 WILSHIRE BLVD  Single-Space     FLAT
33890   NH573     5001 LANKERSHIM BLVD  Single-Space     FLAT

                 RateRange MeteredTimeLimit                    LatLng
33881                $1.00              2HR   (34.14772, -118.364108)
33882                $2.00              1HR  (34.053051, -118.467721)
33883                $1.00              2HR  (34.160238, -118.498197)
33884                $1.00              2HR  (34.147473, -118.429514)
33885  $1.00/H - $4.00/10H             10HR  (34.142651, -118.405806)
33886                $1.00              4HR   (34.14388, -118.361776)
33887                $1.00              2HR  (34.043713, -118.233995)
33888                $1.00              2HR  (34.048555, -118.232501)
33889                $1.00              1HR  (34.046183, -118.464727)
33890                $1.00              2HR  (34.162697, -118.373475)

In [ ]:
import pandas as pd
import re

# Dictionary mapping full street names to abbreviations
full_to_abbreviation = {
    "Street": "St",
    "Avenue": "Ave",
    "Road": "Rd",
    "Boulevard": "Blvd",
    "Drive": "Dr",
    "Lane": "Ln",
    "Way": "Wy",
    "Place": "Pl"
}

# Function to abbreviate full street names (case-insensitive)
def abbreviate_address(address):
    for full_name, abbr in full_to_abbreviation.items():
        address = re.sub(rf'\b{full_name}\b', abbr, address, flags=re.IGNORECASE)  # Case-insensitive replacement
    return address

# Apply function to the entire address column
df[address_column] = df[address_column].astype(str).apply(abbreviate_address)

# Print results
print(df[address_column].head(10))  # Show first 10 updated addresses

0    2100 HILLHURST Ave
1            101 4TH St
2       1601 MARENGO St
3    3500 CAHUENGA Blvd
4        1401 MAPLE Ave
5        3000 PICO Blvd
6      701 DUNSMUIR Ave
7      1200 GLENDON Ave
8      7901 MELROSE Ave
9        700 DETROIT St
Name: BlockFace, dtype: object

In [ ]:
full_street_rows = df[df[address_column].str.contains('|'.join(full_to_abbreviation.keys()), case=False, regex=True)]
print(f"âœ… After reprocessing, the column now has an abbreviated street address format. However, there are {len(full_street_rows)} addresses that are not updating due to typos, spacing, and unrecognizeable characters such as quotations, symbols etc. Consider updating these anomalies before using data set.")
print(f"If there are anomolies to the address column, examples will appear below:")
print(full_street_rows[[address_column]].head(10))  # Show sample of unchanged rows

âœ… After reprocessing, the column now has an abbreviated street address format. However, there are 310 addresses that are not updating due to typos, spacing, and unrecognizeable characters such as quotations, symbols etc. Consider updating these anomalies before using data set.
If there are anomolies to the address column, examples will appear below:
               BlockFace
96   2701 NORTH BROADWAY
148  2601 NORTH BROADWAY
257  2200 NORTH BROADWAY
447  1000 NORTH BROADWAY
467        1400 BROADWAY
489  2701 NORTH BROADWAY
571  2600 NORTH BROADWAY
587         301 BROADWAY
660        2001 BROADWAY
674  2400 NORTH BROADWAY